name: animewatchlist
description: A simple app to display all the anime I had on my 9anime.to watchlist

publish_to: 'none'

version: 0.5.0+11

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animations: ^2.0.0
  cloud_firestore: ^5.2.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6

  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  get_it: ^8.0.3
  injectable: ^2.4.0
  json_annotation: ^4.8.1

  link_preview_generator:
    git:
      url: https://github.com/Juliotati/link_preview_generator.git
      ref: main
  link_target:
    git:
      url: https://github.com/Juliotati/link_target.git
      ref: main
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  url_launcher: ^6.2.5
  url_strategy: ^0.3.0
  web: ^1.1.1

dependency_overrides:
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1

  lint: any

flutter:

  assets:
    - assets/loading_gifs/
  uses-material-design: true
